# Generated by Django 3.2.5 on 2021-12-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meepit', '0002_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
