# Generated by Django 3.2.5 on 2021-12-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meepit', '0003_rename_follower_id_follower_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
